encoding: utf-8
title: Frangiclave Mod Repository
description: >-
  The Frangiclave Mod Repository hosts several mods for the game Cultist Simulator.
logo: "/assets/logo.png"
lang: en-GB
url: "https://mods.thefansus.com"
baseurl: ""
repo: "https://gitlab.com/frangiclave/frangiclave-mod-repository"
css_inline: false

sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Europe/London

markdown: kramdown
theme: alembic-jekyll-theme

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/
  - .gitignore
  - _plugins/

navigation_header:
  Home: /
  Tools: /tools/
  Mods: /mods/
  Submit: /submit/
  Help: /help/

navigation_footer:
  View Repository: https://gitlab.com/frangiclave/frangiclave-mod-repository

frangiclave:
  mod_manager:
    downloads:
      windows: https://gitlab.com/frangiclave/frangiclave-mod-manager/uploads/a8e2a801edd052193185432b12ebeaf3/frangiclave-mod-manager.exe
    version: 0.2.0
